name: WP Engine Deployment

on:
  push:
    branches: [ main, staging, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deployment:
    uses: NU-MarCom/github-actions-templates/.github/workflows/wpengine-deployment.yml@main
    secrets: inherit
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      ENVIRONMENT_URL: ${{ vars.ENVIRONMENT_URL }}
      WPE_ENV: ${{ vars.WPE_ENV }}
      PRD_ENV: ${{ vars.PRD_ENV }}
      STG_ENV: ${{ vars.STG_ENV }}
      DEV_ENV: ${{ vars.DEV_ENV }}
      # Deploy Options
      SRC_PATH: ${{ vars.SRC_PATH }}
      REMOTE_PATH: ${{ vars.REMOTE_PATH }}
      RSYNC_EXCLUDE: ${{ vars.RSYNC_EXCLUDE }}
      PHP_LINT: TRUE
      CACHE_CLEAR: TRUE